---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stressng
  labels:
    app: stressng
spec:
  replicas: 1 # one replica of deployment gets launched
  selector:
    matchLabels:
      app: stressng
  template:
    metadata:
      labels:
        app: stressng
      name: stressng
    spec:
      # nodeName: client1.hand32-249629.bayopsys-pg0.wisc.cloudlab.us - uncomment this to force pod to be deployed on specific node (using `kubectl get nodes` to get list of nodes)
      volumes:
        - name: log-share
          emptyDir: {}
      containers:
        - name: client
          image: ubuntu:latest
          imagePullPolicy: Always
          volumeMounts: # sharing a common file system between two pods launched in the same Deployment
            - mountPath: /log-share/
              name: log-share
          command: ["/bin/bash", "-c"]
          args: ["apt update -y; apt install stress-ng -y; env; stress-ng -c $(CPUS) --cpu-method int64 -t $(TIME)s --log-file /log-share/stress-ng.log; echo '游릭游릭 Done. Sleeping for 30 days 游릭游릭'; sleep 30d;"]
          env:
            - name: TIME
              value: "10"
            - name: CPUS
              value: "22"
        - name: server # launching a second pod
          image: ubuntu:latest
          imagePullPolicy: Always
          volumeMounts: # sharing a common file system between two pods launched in the same Deployment
            - mountPath: /log-share/
              name: log-share	  
          command:
            - '/bin/bash'
            - '-c'
            - >
              echo "游릭游릭 Done. Sleeping for 30 days 游릭游릭";
              sleep 30d;
