apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-geo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: root--geo
  minReplicas: 1
  maxReplicas: 7