apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-mongodb-reservation
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: root--mongodb-reservation
  minReplicas: 1
  maxReplicas: 7