apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-rate
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: root--rate
  minReplicas: 1
  maxReplicas: 6