apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-memcached-reserve
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: root--memcached-reserve
  minReplicas: 1
  maxReplicas: 7