apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-profile
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: root--profile
  minReplicas: 1
  maxReplicas: 7