apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-search
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: root--search
  minReplicas: 1
  maxReplicas: 6