apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-consul
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: root--consul
  minReplicas: 1
  maxReplicas: 7