apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-memcached-profile
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: root--memcached-profile
  minReplicas: 1
  maxReplicas: 7