apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-reservation
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: root--reservation
  minReplicas: 1
  maxReplicas: 6